//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Sasema_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class providers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public providers()
        {
            this.data = new HashSet<data>();
        }
    
        public int provider_id { get; set; }
        public string provider_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string api_key { get; set; }
        public string useragent { get; set; }
        public Nullable<System.DateTime> token_expiry_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data> data { get; set; }
    }
}
