//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Sasema_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int data_id { get; set; }
        public int search_id { get; set; }
        public int provider_id { get; set; }
        public int datatype_id { get; set; }
        public Nullable<System.DateTime> data_timestamp { get; set; }
        public string data_value { get; set; }
    
        public virtual datatypes datatypes { get; set; }
        public virtual providers providers { get; set; }
        public virtual searches searches { get; set; }
    }
}
