//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Sasema_test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class weatherstationEntities : DbContext
    {
        public weatherstationEntities()
            : base("name=weatherstationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data> data { get; set; }
        public virtual DbSet<datatypes> datatypes { get; set; }
        public virtual DbSet<geocodes> geocodes { get; set; }
        public virtual DbSet<providers> providers { get; set; }
        public virtual DbSet<searches> searches { get; set; }
    }

    public partial class CopyOfweatherstationEntities : DbContext
    {
        public CopyOfweatherstationEntities()
            : base("name=CopyOfweatherstationEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<data> data { get; set; }
        public virtual DbSet<datatypes> datatypes { get; set; }
        public virtual DbSet<geocodes> geocodes { get; set; }
        public virtual DbSet<providers> providers { get; set; }
        public virtual DbSet<searches> searches { get; set; }
    }
}
